//package telecom.mss.jt.cg_cgfz;
//
//import java.net.MalformedURLException;
//import java.net.URL;
//import javax.xml.namespace.QName;
//import javax.xml.ws.WebEndpoint;
//import javax.xml.ws.WebServiceClient;
//import javax.xml.ws.WebServiceFeature;
//import javax.xml.ws.Service;
//
///**
// * This class was generated by Apache CXF 3.3.3
// * 2019-09-17T15:45:22.207+08:00
// * Generated source version: 3.3.3
// *
// */
//@WebServiceClient(name = "SI_CGFZSVR_RETURN_MESSAGE_OUT_SynService",
//                  wsdlLocation = "file:/d:/work/webservice/1.wsdl",
//                  targetNamespace = "urn:telecom:mss:jt:cg-cgfz")
//public class SICGFZSVRRETURNMESSAGEOUTSynService extends Service {
//
//    public final static URL WSDL_LOCATION;
//
//    public final static QName SERVICE = new QName("urn:telecom:mss:jt:cg-cgfz", "SI_CGFZSVR_RETURN_MESSAGE_OUT_SynService");
//    public final static QName HTTPSPort = new QName("urn:telecom:mss:jt:cg-cgfz", "HTTPS_Port");
//    public final static QName HTTPPort = new QName("urn:telecom:mss:jt:cg-cgfz", "HTTP_Port");
//    static {
//        URL url = null;
//        try {
//            url = new URL("file:/d:/work/webservice/1.wsdl");
//        } catch (MalformedURLException e) {
//            java.util.logging.Logger.getLogger(SICGFZSVRRETURNMESSAGEOUTSynService.class.getName())
//                .log(java.util.logging.Level.INFO,
//                     "Can not initialize the default wsdl from {0}", "file:/d:/work/webservice/1.wsdl");
//        }
//        WSDL_LOCATION = url;
//    }
//
//    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation) {
//        super(wsdlLocation, SERVICE);
//    }
//
//    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public SICGFZSVRRETURNMESSAGEOUTSynService() {
//        super(WSDL_LOCATION, SERVICE);
//    }
//
//    public SICGFZSVRRETURNMESSAGEOUTSynService(WebServiceFeature ... features) {
//        super(WSDL_LOCATION, SERVICE, features);
//    }
//
//    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation, WebServiceFeature ... features) {
//        super(wsdlLocation, SERVICE, features);
//    }
//
//    public SICGFZSVRRETURNMESSAGEOUTSynService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
//        super(wsdlLocation, serviceName, features);
//    }
//
//
//
//
//    /**
//     *
//     * @return
//     *     returns SICGFZSVRRETURNMESSAGEOUTSyn
//     */
//    @WebEndpoint(name = "HTTPS_Port")
//    public SICGFZSVRRETURNMESSAGEOUTSyn getHTTPSPort() {
//        return super.getPort(HTTPSPort, SICGFZSVRRETURNMESSAGEOUTSyn.class);
//    }
//
//    /**
//     *
//     * @param features
//     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns SICGFZSVRRETURNMESSAGEOUTSyn
//     */
//    @WebEndpoint(name = "HTTPS_Port")
//    public SICGFZSVRRETURNMESSAGEOUTSyn getHTTPSPort(WebServiceFeature... features) {
//        return super.getPort(HTTPSPort, SICGFZSVRRETURNMESSAGEOUTSyn.class, features);
//    }
//
//
//    /**
//     *
//     * @return
//     *     returns SICGFZSVRRETURNMESSAGEOUTSyn
//     */
//    @WebEndpoint(name = "HTTP_Port")
//    public SICGFZSVRRETURNMESSAGEOUTSyn getHTTPPort() {
//        return super.getPort(HTTPPort, SICGFZSVRRETURNMESSAGEOUTSyn.class);
//    }
//
//    /**
//     *
//     * @param features
//     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns SICGFZSVRRETURNMESSAGEOUTSyn
//     */
//    @WebEndpoint(name = "HTTP_Port")
//    public SICGFZSVRRETURNMESSAGEOUTSyn getHTTPPort(WebServiceFeature... features) {
//        return super.getPort(HTTPPort, SICGFZSVRRETURNMESSAGEOUTSyn.class, features);
//    }
//
//}
