package telecom.mss.jt.cg_cgfz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-09-17T15:45:22.133+08:00
 * Generated source version: 3.3.3
 *
 */
@WebService(targetNamespace = "urn:telecom:mss:jt:cg-cgfz", name = "SI_CGFZSVR_RETURN_MESSAGE_OUT_Syn")
@XmlSeeAlso({ObjectFactory.class})
public interface Sicgfzsvrreturnmessageoutsyn {

    @WebMethod(operationName = "XXX_MT_PROVIDER_FEEDBACK", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "XXX_MT_PROVIDER_FEEDBACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTPROVIDERFEEDBACK")
    @ResponseWrapper(localName = "XXX_MT_PROVIDER_FEEDBACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTPROVIDERFEEDBACKResponse")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    public EIACBACKRESPONSE xxxMTPROVIDERFEEDBACK(

            @WebParam(name = "I_REQUEST", targetNamespace = "")
                    PROVIDER iREQUEST
    );

    @WebMethod(operationName = "XXX_MT_PURCHASE_ORDER_BACK", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "XXX_MT_PURCHASE_ORDER_BACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTPURCHASEORDERBACK")
    @ResponseWrapper(localName = "XXX_MT_PURCHASE_ORDER_BACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTPURCHASEORDERBACKResponse")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    public EIACBACKRESPONSE xxxMTPURCHASEORDERBACK(

            @WebParam(name = "I_REQUEST", targetNamespace = "")
                    PURHCASEORDERBACKREQUEST iREQUEST
    );

    @WebMethod(operationName = "XXX_MT_MATERIAL_FEEDBACK", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "XXX_MT_MATERIAL_FEEDBACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTMATERIALFEEDBACK")
    @ResponseWrapper(localName = "XXX_MT_MATERIAL_FEEDBACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTMATERIALFEEDBACKResponse")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    public EIACBACKRESPONSE xxxMTMATERIALFEEDBACK(

            @WebParam(name = "I_REQUEST", targetNamespace = "")
                    PROVIDER iREQUEST
    );

    @WebMethod(operationName = "XXX_MT_MATCONFIG_FEEDBACK", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "XXX_MT_MATCONFIG_FEEDBACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTMATCONFIGFEEDBACK")
    @ResponseWrapper(localName = "XXX_MT_MATCONFIG_FEEDBACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTMATCONFIGFEEDBACKResponse")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    public EIACBACKRESPONSE xxxMTMATCONFIGFEEDBACK(

            @WebParam(name = "I_REQUEST", targetNamespace = "")
                    PROVIDER iREQUEST
    );

    @WebMethod(operationName = "XXX_MT_CHANGE_PURCHASE_ORDER_BACK", action = "http://sap.com/xi/WebService/soap1.1")
    @RequestWrapper(localName = "XXX_MT_CHANGE_PURCHASE_ORDER_BACK", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTCHANGEPURCHASEORDERBACK")
    @ResponseWrapper(localName = "XXX_MT_CHANGE_PURCHASE_ORDER_BACKResponse", targetNamespace = "urn:telecom:mss:jt:cgfz", className = "telecom.mss.jt.cg_cgfz.XXXMTCHANGEPURCHASEORDERBACKResponse")
    @WebResult(name = "E_RESPONSE", targetNamespace = "")
    public EIACBACKRESPONSE xxxMTCHANGEPURCHASEORDERBACK(

            @WebParam(name = "I_REQUEST", targetNamespace = "")
                    PURHCASEORDERBACKREQUEST iREQUEST
    );
}
