project:
  name: 本机环境

server:
  port: 8081

spring:
  dubbo:
    application:
      name: goods-consume
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.chenm.demo

jmx:
  enabled: false

