project:
  name: 本机环境

server:
  port: 8080

spring:
  dubbo:
    application:
      name: goods-provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20889
    scan: com.chenm.demo

jmx:
  enabled: false

